announcements/urls.py
from django.urls import path

from . import feeds, views

app_name = "announcements"
urlpatterns = [
    path("", views.AnnouncementListView.as_view(), name="list"),
    path("feed/", feeds.AnnouncementFeed(), name="feed"),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "category/<slug:slug>/",
        views.ServiceCategoryDetailView.as_view(),
        name="service-category-detail",
    ),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

# Tweak the admin site.
admin.site.site_header = "SHIP Haven administration"
admin.site.site_title = "SHIP Haven admin"

urlpatterns = [
    path("", include("core.urls")),
    path("announcements/", include("announcements.urls")),
    path("shipyard/", admin.site.urls),
]

# Enable the debug toolbar only in DEBUG mode.
if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

announcements/models.py
from django.db import models


class Announcement(models.Model):
    """An announcement to broadcast to the community."""

    title = models.CharField(max_length=128)
    description = models.TextField()
    expires_at = models.DateTimeField(db_index=True)

    class Meta:
        ordering = ["-expires_at"]

    def __str__(self):
        return self.title

core/models.py
from django.db import models
from ordered_model.models import OrderedModel


class ServiceCategory(OrderedModel):
    """Each service must belong to a category for easy browsing."""

    name = models.CharField(max_length=128)
    slug = models.SlugField(
        help_text="This is the unique name that will display in the URL."
    )
    description = models.TextField(default="")
    icon = models.CharField(
        max_length=128,
        help_text=(
            "Upload a 300px x 300px to the 'static' directory. Add file path here."
        ),
        default="",
    )
    COLOR_CHOICES = (
        ("red", "Red"),
        ("teal", "Teal"),
        ("orange", "Orange"),
        ("purple", "Purple"),
        ("green", "Green"),
        ("indigo", "Indigo"),
        ("yellow", "Yellow"),
        ("gray", "Gray"),
    )
    color = models.CharField(max_length=8, choices=COLOR_CHOICES, default="gray")

    class Meta(OrderedModel.Meta):
        verbose_name_plural = "service categories"

    def __str__(self):
        return self.name


class Service(OrderedModel):
    """A community service that is available to homeless citizens."""

    name = models.CharField(max_length=128)
    organization_name = models.CharField(max_length=128, default="")
    description = models.TextField()
    website = models.URLField(default="", blank=True)

    street_address = models.CharField(max_length=256, default="")
    city = models.CharField(max_length=128, default="")
    state = models.CharField(max_length=32, default="")
    zip_code = models.CharField(max_length=16, default="")
    latitude = models.CharField(max_length=16, default="", blank=True)
    longitude = models.CharField(max_length=16, default="", blank=True)

    operating_hours = models.CharField(max_length=256, blank=True)
    phone_number = models.CharField(max_length=32, blank=True)
    email = models.EmailField(blank=True)
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)

    # Services should be orderable within their category.
    order_with_respect_to = "category"

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.name

announcements/views.py
from django.utils import timezone
from django.views.generic import ListView

from .models import Announcement


class AnnouncementListView(ListView):
    def get_queryset(self):
        return Announcement.objects.filter(expires_at__gte=timezone.now())

core/views.py
from django.views.generic import DetailView, ListView
from django.utils import timezone

from announcements.models import Announcement

from .models import Service, ServiceCategory


class IndexView(ListView):
    queryset = ServiceCategory.objects.all()
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["announcements"] = Announcement.objects.filter(
            expires_at__gte=timezone.now()
        )
        return context


class ServiceCategoryDetailView(DetailView):
    model = ServiceCategory

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["services"] = Service.objects.filter(category=self.object)
        return context

templates/announcements/announcement_list.html
{% extends "base.html" %}

{% block main %}
  <section class="text-lg bg-gray-100 border-b pt-5 pb-5 h-auto">
    <div class="w-full p-6 pb-1 -mt-6 text-2xl text-center font-extrabold text-blue-900"> <h2 class="">Current Announcements</h2></div>
    <div class="flex items-center justify-center">
      <div class="w-full p-6 mt-6">
        {% if announcement_list %}
          {% for announcement in announcement_list %}
            <div id="announcement-{{ announcement.id }}"class="px-4 py-3 mx-2 mt-2 mb-2 border-t-8 border-blue-800 text-gray-800 " >
              <p class="font-bold uppercase text-xs text-gray-600">Announcement</p>
              <p class="font-bold text-xl text-gray-800 ">{{ announcement.title }}</p>
              <p class="text-l  text-gray-800">{{ announcement.description }}</p>
            </div>
            {# TODO: If we can get back callout and URL, then great. #}
            {# {% if announcement.callout %} #}
            {#   <div class="px-4 py-3 mx-2 mt-4 mb-2" > #}
            {#     <div id="url" class="text-md text-left p-1 bg-gray-500 ripple rounded-md mb-1"> #}
            {#       <a class="text-sm text-left p-2 flex" href="{{ announcement.url }}" target="_blank"> #}
            {#         <span class="mr-2"> #}
            {#           <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"><path class="heroicon-ui" d="M4.06 13a8 8 0 0 0 5.18 6.51A18.5 18.5 0 0 1 8.02 13H4.06zm0-2h3.96a18.5 18.5 0 0 1 1.22-6.51A8 8 0 0 0 4.06 11zm15.88 0a8 8 0 0 0-5.18-6.51A18.5 18.5 0 0 1 15.98 11h3.96zm0 2h-3.96a18.5 18.5 0 0 1-1.22 6.51A8 8 0 0 0 19.94 13zm-9.92 0c.16 3.95 1.23 7 1.98 7s1.82-3.05 1.98-7h-3.96zm0-2h3.96c-.16-3.95-1.23-7-1.98-7s-1.82 3.05-1.98 7zM12 22a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/></svg> #}
            {#         </span> #}
            {#         More info / {{ announcement.callout }} #}
            {#       </a> #}
            {#     </div> #}
            {#   </div> #}
            {# {% endif %} #}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" class="bg-white subpixel-antialiased">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  <link href="{% static "manifest.json" %}" rel="manifest">
  <title>SHIP Haven</title>
  <style>
.xx-YES, .xx-1 {border-color: #c53030 !important;}
.xborder .xx-YES {border-color: #c53030 !important;}

.ripple {
  background-position: center;
  transition: background 0.5s;
}
.ripple:hover {
  background: #cbd5e0 radial-gradient(circle, transparent 1%, #cbd5e0 1%) center/15000%;
}
.ripple:active {
  background-color: var(--active-color);
  background-size: 100%;
  transition: background 0s;
}
  </style>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-175266872-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-175266872-1');
  </script>
</head>
<body class="min-h-screen flex flex-col">

  <main class="container mx-auto flex-grow">
    <div class="flex flex-row items-stretch justify-between pl-4">
      <a href="{% url "core:index" %}">
        <img class="h-10 my-3" src="{% static "logos/line-logo.png" %}" alt="SHIP Haven logo">
      </a>
      <div class="text-center">
        <a href="tel:211" class="h-16 inline-flex items-center bg-red-700 text-white font-semibold py-2 px-4 text-md">
          <img class="h-16" src="{% static "crisis.png" %}" alt="Call for help">
        </a>
      </div>
    </div>

    {% block main %}{% endblock %}
  </main>

  <section class="bg-gray-100 border-b pt-5 pb-5 h-auto">
    <div class="flex flex-wrap flex-col-reverse sm:flex-row items-center justify-center">
      <div class="w-full text-center sm:w-1/2 p-6 mt-6">
        <img class="hover:opacity-75 h-32 m-auto pb-5"  src="{% static "frederick-county.png" %}" alt="Frederick County icon">

        <div class="text-gray-900 font-bold text-xl mb-2">Sign up to receive announcements.</div>
        <div class="text-gray-700 text-base">
          <form action="https://shipfrederick.us10.list-manage.com/subscribe/post?u=fceb2fa00c7e8723b4bba0ee9&id=5af450fae4" method="POST">
            <input type="email" name="EMAIL"
              class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
              placeholder="Your email address" required>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_fceb2fa00c7e8723b4bba0ee9_5af450fae4" tabindex="-1" value=""></div>
            <input type="submit" value="Sign Up" class="bg-blue-600 hover:bg-blue-700 text-white font-bold mt-4 py-2 px-4 rounded focus:outline-none focus:shadow-outline">
          </form>
        </div>
      </div>
  </section>

  <footer class="container mx-auto  px-8">
    <div class="w-full flex flex-col md:flex-row py-6">
      <div class="flex-1 mb-6">
        <p class="font-bold text-gray-800 mb-2">
          <a class="text-blue-700" href="https://shipfrederick.com/">SHIP of Frederick County</a>
          provides urgent services and critical support
          for the hundreds of youth experiencing homelessness
          in Frederick County each year.
        </p>
        <p class="font-bold text-gray-800 mb-2">
          SHIP believes in the power of education
          to transform these young people’s lives.
        </p>
        <p class="text-gray-800">&copy; {% now "Y" %} SHIP of Frederick County<p>
        <a href="https://www.freepik.com/free-photos-vectors/background target="_blank"" class="text-xs text-gray-500">Icons by freepik - www.freepik.com</a>
      </div>
    </div>
  </footer>

</body>
</html>

templates/core/index.html
{% extends "base.html" %}
{% load static %}

{% block main %}

  <section class="bg-red-700 border-b mt-2 pt-5 pb-5 h-auto">
    <a href="tel:211">
      <div class="flex flex-row items-start justify-center mr-4">
          <img class="hover:opacity-75 h-24"  src="{% static "crisis-211.png" %}" alt="emergency operator icon">

          <div class="text-white">
            <h3 class="font-bold text-xl mb-2">Do you need immediate help or just have a question?</h3>
            <p class="text-white text-base">Maryland’s Helpline is available 24/7 to provide support, guidance, and assistance.
            Please <span class="font-bold" href="tel:211">call 211</span> and select option 1, text your zip code to 898-211, or visit 211MD.org </p>
          </div>
      </div>
    </a>
  </section>

  <section class="container mx-auto flex flex-wrap pt-4 pb-8 bg-white">
    <div class="w-full pb-1 text-2xl text-center font-extrabold text-blue-900">
      <h2 id="services" class="">
        Services and Support
      </h2>
    </div>

    {% for category in servicecategory_list %}
      <div class="w-full md:w-1/3 xl:w-1/3 p-4 flex flex-col">
        <div class="flex flex-wrap flex-col-reverse content-between sm:flex-row text-gray-800" >
          <a class="w-full self-center" href="{% url "core:service-category-detail" category.slug %}">
            <img class="w-full bg-{{ category.color }}-500 ripple object-cover shadow-lg"  src="{% static category.icon %}" alt="{{ category.name }}">
            <div class="p-4">
              <h3 class="font-bold">{{ category.name }}</h3>
              <p class="font-light">{{ category.description }}</p>
            </div>
          </a>
        </div>
      </div>
    {% endfor %}

  </section>

  {% if announcements %}
    <section class="bg-gray-300 border-b p-2 h-auto">
      <div class="flex flex-wrap flex-col-reverse sm:flex-row items-center justify-center">
        <div class="w-full sm:w-1/2 py-6">
            {% for announcement in announcements %}
              <div class="px-4 py-3 mx-2 mt-4 mb-2 border-t-8 border-blue-800 text-gray-800 " >
                <p class="font-bold uppercase text-xs text-gray-600">Announcement</p>
                <p class="font-bold text-xl">{{ announcement.title }}</p>
                <p class="text-l">
                  {{ announcement.description|truncatewords:25 }}
                  <a class="font-bold uppercase text-xs text-blue-600"
                    href="{% url "announcements:list" %}#announcement-{{ announcement.id }}">
                    Continue Reading</a>
                </p>
              </div>
            {% endfor %}
        </div>
      </div>
    </section>
  {% endif %}

{% endblock %}

templates/core/servicecategory_detail.html
{% extends "base.html" %}
{% load static %}

{% block main %}
  <script>
    function selectMap(latitude, longitude) {
      var url = "maps.google.com/maps?daddr=" + latitude + "," + longitude + "&amp;ll=";
      if ((navigator.platform.indexOf("iPhone") !== -1) ||
          (navigator.platform.indexOf("iPad") !== -1) ||
          (navigator.platform.indexOf("iPod") !== -1)) {
        window.open("maps://" + url);
      }
      window.open("https://" + url);
    }
  </script>

  <section class="bg-{{ servicecategory.color }}-500 border-b pt-5 pb-5 h-auto text-white ">
    <div class="flex flex-wrap flex-col-reverse sm:flex-row items-center justify-center">
      <div class="w-full text-center sm:w-1/2 p-4">
        <img class="h-48 m-auto pb-5"  src="{% static servicecategory.icon %}">
        <h1 class="font-bold text-2xl pb-2 border-b mb-2">{{ servicecategory.name }}</h1>
        <p class="font-light leading-tight text-xl">{{ servicecategory.description }}</p>
      </div>
    </div>
  </section>

  <section class="bg-{{ servicecategory.color }}-100">
    {% for service in services %}
      <div class="border-b pt-5 pb-5 h-auto">
        <div class="flex flex-wrap flex-col-reverse sm:flex-row items-center justify-center">
          <div class="w-full sm:w-1/2 p-4">

            <div class="px-4 py-3 mt-4 mb-2 border-t-8 text-gray-800 border-{{ servicecategory.color }}-500">
              <p class="font-bold uppercase text-xs text-gray-600 mb-1">{{ service.organization_name }}</p>
              <p class="font-bold leading-none text-2xl mb-2">{{ service.name }}</p>
              <p class="text-l">{{ service.description }}</p>
            </div>

            <p class="text-gray-800 font-bold uppercase text-xs">
              More Information on {{ service.name }}
            </p>

            <div class="text-white p-5">

              {% if service.street_address %}
                <div class="text-md text-left p-1 bg-{{ servicecategory.color }}-500 ripple rounded-md mb-2">
                  {% if service.latitude and service.longitude %}
                    <div class="text-md text-left p-2 flex" onclick="selectMap('{{ service.latitude }}', '{{ service.longitude }}')">
                      <span class="mr-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M5.64 16.36a9 9 0 1 1 12.72 0l-5.65 5.66a1 1 0 0 1-1.42 0l-5.65-5.66zm11.31-1.41a7 7 0 1 0-9.9 0L12 19.9l4.95-4.95zM12 14a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/></svg>
                      </span>
                      {{ service.street_address }}, {{ service.city }}, {{ service.state }} {{ service.zip_code }}
                    </div>
                  {% else %}
                    <a class="text-md text-left p-2 flex" href="https://maps.google.com/maps?q={{ service.street_address }}, {{ service.city }}, {{ service.state }} {{ service.zip_code }}">
                      <span class="mr-2">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M5.64 16.36a9 9 0 1 1 12.72 0l-5.65 5.66a1 1 0 0 1-1.42 0l-5.65-5.66zm11.31-1.41a7 7 0 1 0-9.9 0L12 19.9l4.95-4.95zM12 14a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/></svg>
                      </span>
                      {{ service.street_address }}, {{ service.city }}, {{ service.state }} {{ service.zip_code }}
                    </a>
                  {% endif %}
                </div>
              {% endif %}

              {% if service.operating_hours %}
                <div id="hours" class="text-md text-left p-1 bg-{{ servicecategory.color }}-500 rounded-md mb-2">
                  <div class="text-md text-left p-2 flex">
                    <span class="mr-2">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M12 22a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16zm1-8.41l2.54 2.53a1 1 0 0 1-1.42 1.42L11.3 12.7A1 1 0 0 1 11 12V8a1 1 0 0 1 2 0v3.59z"/></svg>
                    </span>
                    {{ service.operating_hours }}
                  </div>
                </div>
              {% endif %}

              {% if service.phone_number %}
                <div id="phone" class="text-md text-left p-1 bg-{{ servicecategory.color }}-500 ripple rounded-md mb-2">
                  <a class="text-md text-left p-2 flex" href="tel:{{ service.phone_number }}">
                    <span class="mr-2">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M13.04 14.69l1.07-2.14a1 1 0 0 1 1.2-.5l6 2A1 1 0 0 1 22 15v5a2 2 0 0 1-2 2h-2A16 16 0 0 1 2 6V4c0-1.1.9-2 2-2h5a1 1 0 0 1 .95.68l2 6a1 1 0 0 1-.5 1.21L9.3 10.96a10.05 10.05 0 0 0 3.73 3.73zM8.28 4H4v2a14 14 0 0 0 14 14h2v-4.28l-4.5-1.5-1.12 2.26a1 1 0 0 1-1.3.46 12.04 12.04 0 0 1-6.02-6.01 1 1 0 0 1 .46-1.3l2.26-1.14L8.28 4zm7.43 5.7a1 1 0 1 1-1.42-1.4L18.6 4H16a1 1 0 0 1 0-2h5a1 1 0 0 1 1 1v5a1 1 0 0 1-2 0V5.41l-4.3 4.3z"/></svg>
                    </span>
                    {{ service.phone_number }}
                  </a>
                </div>
              {% endif %}

              {% if service.email %}
                <div id="email" class="text-md text-left p-1 bg-{{ servicecategory.color }}-500 ripple rounded-md mb-2">
                  <a class="text-md text-left p-2 flex" href="mailto:{{ service.email }}">
                    <span class="mr-2">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M15.6 15.47A4.99 4.99 0 0 1 7 12a5 5 0 0 1 10 0v1.5a1.5 1.5 0 1 0 3 0V12a8 8 0 1 0-4.94 7.4 1 1 0 1 1 .77 1.84A10 10 0 1 1 22 12v1.5a3.5 3.5 0 0 1-6.4 1.97zM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/></svg>
                    </span>
                    {{ service.email }}
                  </a>
                </div>
              {% endif %}

              {% if service.website %}
                <div id="url" class="text-md text-left p-1 bg-{{ servicecategory.color }}-500 ripple rounded-md mb-2">
                  <a class="text-md text-left p-2 flex" href="{{ service.website }}" target="_blank">
                    <span class="mr-2">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M4.06 13a8 8 0 0 0 5.18 6.51A18.5 18.5 0 0 1 8.02 13H4.06zm0-2h3.96a18.5 18.5 0 0 1 1.22-6.51A8 8 0 0 0 4.06 11zm15.88 0a8 8 0 0 0-5.18-6.51A18.5 18.5 0 0 1 15.98 11h3.96zm0 2h-3.96a18.5 18.5 0 0 1-1.22 6.51A8 8 0 0 0 19.94 13zm-9.92 0c.16 3.95 1.23 7 1.98 7s1.82-3.05 1.98-7h-3.96zm0-2h3.96c-.16-3.95-1.23-7-1.98-7s-1.82 3.05-1.98 7zM12 22a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/></svg>
                    </span>
                    {{ service.organization_name }}
                  </a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </section>

{% endblock %}